### ISSUE TITLE
Need to track IP addresses to prevent multi-accounts

### ISSUE THREAD

**Issue by qark** [ospaceteam/outerspace#13]
Outer Space server now does not track IP addresses which makes it very hard to detect multiple accounts of a single player playing in one galaxy.

**Comment by SummerGram** [comment]
Is it still open?

**Comment by dahaic** [comment]
@SummerGram hmm! Good question. Few months ago, I would say it is. With the GDPR [1] in effect now, I would say it's too complicated matter which outweights benefits. (Not to mention easiness with which it is possible to proxy connections these days).

So the answer is no, lets not follow this path.

[1] https://eugdprcompliant.com/personal-data/
