### ISSUE TITLE
Removing option to scrap ships / fleets

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#139]
I do not see any reason why should player do that, apart from obscure "scrapping scout before landing on planet, so nobody knows I am scouting", as that's twitchy and stupid.

And possibly "scrapping attack fleet, as I send it by accident and I don't want to attack this neighbor and there is no way to communicate with them before fleet lands". If this is needed, it should be separate feature.

**Comment by temuchin-** [comment]
Not sure about scrapping fleets, except to get rid of any really heavy accidental builds in late game (say you went way overboard on a build option & need to shift production which now sits at about zero empire wide). Had that happen once in a late game empire takeover, comp player (CP) had either been rebel faction all along or had devolved the empire fleets. Regardless i came in w/ nearly 0 production and heavily degraded research.

In other news --- Thank you for cleaning up the some of the code & even having comments it makes it much easier to parse.

**Comment by dahaic** [comment]
It should be relatively easy to get rid of fleets by sending them away or in extreme case by scrapping whole design. Dangerous buttons are removed for now.
