### ISSUE TITLE
Make planet slots produce energy and biomatter

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#143]
By having some baseline production of both, we can later on move to the distribution of biomatter/energy spread over all buildings by the same portion - removing the necessity to order buildings on the planets.

Idea is to have something like 1 biomatter (population of 100) and 5 energy per slot.

**Comment by dahaic** [comment]
This way, player won't lose planets without buildings. This needs to be dealt with, either by providing population with very small production (for ability to rebuild) or option to abandon colony. I feel a bit better about having small population-based production. (1 CP per 1000 pop?)

**Comment by dahaic** [comment]
Population-based production will be hard to work right with small planets / populations. Changing proposal for 1 CP per planet slot.

**Comment by temuchin-** [comment]
you might solve this with adding a job task like (basic sustenance) job. It would be a pain, it would have to be available only when no buildings were present be a kludge to grow pop needs plus 2% or something.

Also keep in mind you want to be able to let planets die off. This can be a problem when you have a population at low pop & low morale w/ enemy fleets in the area. If the pop dies off you can repopulate quickly w/ colony ships and start a simple build queue of defenses. So we might also wind up breaking a viable strategy / tactical challenge.

**Comment by dahaic** [comment]
Final implementation is 5 CP on every planet. Let's see where it gets us. :)
Dynamic baseline was rejected because bigger planets are so much better already - it would be too good for lucky players starting with large planets in the vicinity.
