### ISSUE TITLE
config.ini for vip.password option is a bit confusing

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#167]
created server/var/config.ini containing
vip.password = "testing"

the vip.password option does not seem to function. I am certain the problem lies on my side & even if it isn't ; I will be unable to solve this w/o guidance. Only note on this is from quark in 2012 in changelog.

I would like to be able to stress test things as the pirates.

A bit of background on what  i am currently doing; which is testing 2 servers (srvr A has 1 legacy game, 1 9P game , srvr B has 2 9P games 1 single player) (yes I had to hardcode different port numbers, which is something that should be part of the configuration file /dir options for the universe ; ) the idea is to stress test universe A as a baseline & universe B is where I tweak things, for game /  galaxy options & game balance. The biggest problem is I am not exactly sure how I can change galaxy constants w/o having to change outerspace server settings (hence 2 separate servers) This might be an issue of the piece not existing yet ( I had assumed the var/config.ini file was that piece w/ the only evidence being one comment by quark 6 years ago referencing vip.password for taking over pirate faction)

**Comment by dahaic** [comment]
Good point, server should populate this with some default value. What you actually have to do (and no, it's not documented, I had to read the code) is to include this into `osci.ini` in your configdir:

```
[vip]
password = yarr!
```

**Comment by temuchin-** [comment]
configured player osci.ini as shown. Reloaded client it still fails. the failure is local (never touches the server when checking the vip password) will check to see if anything in the client side has been broken.

(wound up going through old code ; lukc & sourceforge code. Thank you for reformatting the order of that. Things flow in a more logical way now.)

**Comment by dahaic** [comment]
Actually now both server and client uses the same default config file name, so you have to edit `osci.ini` in your server configdir. (But both client and server can coexist within the same directory). Don't forget to restart the server so the configuration is applied.

**Comment by temuchin-** [comment]
I wondered about that, though it seemed the entire operation was happening client side. Then you mentioned the osci.ini file & that clinched it, I knew it was a client side operation. It works as designed now. This brings up a whole slew of things,,, which will be revisited elsewhen. Probably under the splitting server & client functions feature section, later. Thanks again.

**Comment by temuchin-** [comment]
I'm closing this, parts of it might need to be under the above mentioned splitting server & client feature.
