### ISSUE TITLE
Renegade to refuel ships with core structures

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#205]
Current weak point of Renegade is Cosmodrome - if it is bombed, whole fleet will run out of fuel and disappear. That's not the intended behavior. Thus proposal is to make Cosmodrome the only repair facility, and add refuel to RENEGADEBASE line of structures.

**Comment by temuchin-** [comment]
refuelMax="20"
			refuelInc="1"
# the standard happy crappy bare minimum refuel ability in the game.
# now patch it to every renegade device you can imagine
	<technology id="9060" symbol="RENEGADEBASE2" name="Renegade Base">
		<discovery
			researchMod="1.0 + 0.5"
			researchRaces="r"
			level="99"
		/>
		<structure
			buildProd="1920"
			prodBio="30"
			prodBioMod="0.0,0.0,0.0,1.0"
			prodProd="30"
			prodProdMod="0.0,0.3,0.0,0.7"
			prodEn="30"
			prodEnMod="0.0,0.0,0.0,1.0"
			operWorkers="2000"
			scannerPwr="50"
			maxHP="600"
			refuelMax="20"
			refuelInc="1"
			combatAtt="6"
			revoltThr="-100"
			structWeapons="6,0,0,0,1"
			unpackPop="2000"
			finishConstrHandler="finishStructOUTPOST"
			isMilitary="1"
			fullInfo="1"
		/>
	</technology>
	<technology id="9061" symbol="RENEGADEBASE2MINOR" name="Renegade Camp">
		<discovery
			researchMod="1.0 + 0.5"
			researchRaces="r"
			level="99"
		/>
		<structure
			buildProd="480"
			prodBio="30"
			prodBioMod="0.0,0.0,0.0,1.0"
			prodProd="10"
			prodProdMod="0.0,0.3,0.0,0.7"
			prodEn="30"
			prodEnMod="0.0,0.0,0.0,1.0"
			operWorkers="500"
			scannerPwr="50"
			maxHP="250"
			combatAtt="6"
			refuelMax="20"
			refuelInc="1"
			structWeapons="2,0,0,0,1"
			isMilitary="1"
			fullInfo="1"
		/>
	</technology>
	<technology id="9062" symbol="RENEGADEBASE3" name="Renegade HQ">
		<discovery
			researchMod="1.0 + 0.5"
			researchRaces="r"
			level="99"
		/>
		<structure
			buildProd="3280"
			prodBio="60"
			prodBioMod="0.0,0.0,0.0,1.0"
			prodProd="40"
			prodProdMod="0.0,0.3,0.0,0.7"
			prodEn="30"
			prodEnMod="0.0,0.0,0.0,1.0"
			operWorkers="4000"
			scannerPwr="50"
			maxHP="1200"
			combatAtt="6"
			refuelMax="20"
			refuelInc="1"
			moraleTrgt="+50"
			revoltThr="-100"
			structWeapons="10,0,0,0,1"
			unpackPop="4000"
			finishConstrHandler="finishStructOUTPOST"
			isMilitary="1"
			fullInfo="1"
		/>
	</technology>
	<technology id="9063" symbol="RENEGADEBASE3MINOR" name="Renegade Fort">
		<discovery
			researchMod="1.0 + 0.5"
			researchRaces="r"
			level="99"
		/>
		<structure
			buildProd="1020"
			prodBio="30"
			prodBioMod="0.0,0.0,0.0,1.0"
			prodProd="15"
			prodProdMod="0.0,0.3,0.0,0.7"
			prodEn="30"
			prodEnMod="0.0,0.0,0.0,1.0"
			operWorkers="1000"
			scannerPwr="50"
			maxHP="500"
			combatAtt="6"
			refuelMax="20"
			refuelInc="1"
			structWeapons="3,0,0,0,1"
			isMilitary="1"
			fullInfo="1"
		/>
	</technology>
# Done
