### ISSUE TITLE
Renegade to utilize strategic resource

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#206]
Renegade defends strategic resource, why not to differentiate a bit based on the SR it possess?

Proposal:
* Titanium - Bigger, stronger medium hull (called Cruiser)
* Uranium - Nuclear STL engine, effectively medium hull with higher attack and defence ratings (called Destroyer)

**Comment by temuchin-** [comment]
Nuclear STL
			storEn="3840"/16=240 probably divide this by 4 ~=60
			operEn="32"/16 =2
			slots="16" /16 = 1
			weight="16"/16 = 1

This leaves much to solve, it also means you should something from the following
A) allow resource collection twice a week (every 3 days)
B) grant renegade faction the ability to (and desire) to nuclear fuse strategic elements
C) start renegade faction w/ a huge reserve of said strategic element.

so the item might look something like this (used fission engine as basis /16 (except for eng power /8)
		<shipequip
			subtype="seq_eng"                 ????? "stl_eng"????
			buildProd="112"
			buildSRes="SR_TL1A:SR_AMOUNT_SMALL"
			storEn="90"
			operEn="2"
			slots="1"
			weight="1"
			engPwr="96"
			signature="0"
		/>
