### ISSUE TITLE
Implement STL drives

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#207]
STL drive affects only the "in system" speed, i.e. attack and defence ratings, but does not alter FTL speed. With proper sizing and pricing, it can make interesting balance with use of FTL drive. (Achieving similar battle capability should be cheaper using STL than pure FTL)

**Comment by temuchin-** [comment]
I like the idea. Recommend 1 space 1 wgt for initial testing. Not sure how much this helps overall design efficiency. Right now all 3 types when building ships, are better served by adding an engine than adding fuel tanks/cells.
So this brings up the 1st question, should STL have fuel storage?? if so they replace fuel tanks. Or should fuel tanks be more efficient? Will need to break out a variable for combat speed, to differentiate from FTL speed. or maybe breakt out a separate FTL speed as that might be less work to code through.

**Comment by dahaic** [comment]
Hi, thanks for feedback. This feature is meant as a way to make system defenses viable and also "believable". By that I mean ships either without ftl capabilities or with trivial ones. With that in mind, I would propose to not put these engines into fuel calculation at all. So no fuel capacity nor fuel consumption.

**Comment by temuchin-** [comment]
What I sometimes do as Cyborg player, psionic beacon 4 nanoweb armor all the weapons (maybe fuel tank). Done. As long as I have a space dock at the planet the ships do just fine. only problem is that it only decreases the value of a ship by very little.

**Comment by temuchin-** [comment]
maybe we should have "make system defenses viable," better defined. if the desire is to build monitors (heavily armed platforms w/ no go juice but with system engines, famous in the traveller universe). right now that is possible, but honestly engines add almost no cost to a ship. The only benefit to be received is if a player looks under the hood and realizes that renegade ships can FTL, so it would be a flavor fail.
Which means do we increase engine cost on ships as any large powered structure is dominated by 70% engine/fuel minimum in mass , size, initial resources to build, & in resources to maintain? And this only gets worse as you scale up, even factoring in having 'usually' lower gravity fights (gravity wells suck) to work against.     This means the entire engine system will have to be revamped (less labor intensive than retooling all the other components). I'm also ignoring the handwaving of engines are just as efficient if you have one, two, fifteen, or fifty. The engineer in me bristles but I handwave it away as "game mechanics."

Maybe the above change proposed (if carefully balanced), will gain the desired result. W/O having to rebuild the entire ship system.

**Comment by dahaic** [comment]
Yeah, I meant something like monitors, or system-bound squadrons.
I have to disagree with statement that "engines add almost no cost to a ship". In early phases of the game, engines are between one half and one third of costs. And if you want to have highly mobile force or you want high ATT/DEF stats, it might be much worse. That's significant portion, in my books.

For the RCS idea - I'll probably stick to have engines with in system engine power (resulting in battle speed defining ATT, DEF and MDEF). Behavior differs with ship sizes - RCS adds 4 DEF, and that is applied directly for small ships, and one third to large ships. (1.33)

If I alter system engine power, 1 STL gives small hull some ATT. And you have to put 4 STL engines on large hull to have that one third effect that is already part of balancing. And this (rather brutal) increase in costs is in line with how are small/medium/large ships balanced at the moment.

**Comment by dahaic** [comment]
Final implementation makes STL engines with 2 slots, 1 weight and 60 engine power (on 1-5), for the price of 120 CP. So when compared with FTL (sublevel 5):
```
FTL: 4 slots, 4 weight, 80 pwr, 240 CP
2x STL: 4 slots, 2 weight, 120 pwr, 240 CP
Nuclear STL: 4 slots, 2 weight, 150 pwr, 240 CP, 0.1 Uranium
```
When experimented with various designs, defensive forces will definitely want to utilize some STL drives to get edge over enemy. For attacking force.. we'll see. It all depends on FTL speed your strategy dictates. If fleets are build to speed 5, there is definitely some space to utilize STL to make them more effective in battle, especially for medium/large sized ships.
