### ISSUE TITLE
Bug in Planet Manager when sorting

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#212]
When sorting planets (Env Min En Bio+- Free Slots Diam Morale CP RP ETC Tot. Etc) for any aforementioned column listed it produces the following bug .
python2.7/re.py, line 167, in split
 return_compile(pattern, flags).split(string, maxsplit)
TyepError: expected string or buffer

It occurs in PlanetsOverviewDlg.py
When you go to resort any of the listed columns.
The game is single player, the galaxy has started to run, but no turns have been processed yet.
This one should be easy to reproduce.

The following columns still sort (planet, type, constructing).

**Comment by temuchin-** [comment]
It also occurs in Research menu. Once again the inner variables (Lvl Str SH). So that takes the problem back to Listbox.py (or it might go further. Will look at it later.

**Comment by dahaic** [comment]
I can confirm the bug. Thanks for report!
