### ISSUE TITLE
Bug Ship Building / Feature fun

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#215]
When building ships the dialog will randomly not add in or account for equipment that is there.
This can be verified by reloading ship design & having it come up correct. Whereas the last time it might show it missing slots, missing HP.

Sometimes when you open ship dialog it shows name of last ship in design section (no equipment, nothing else just the name). This means until you click new design to clear the queue, what you add to the ship will have no relation to what the ship will actually have, & usually missing the control module you installed)

Design section feels wonky with the hiccups (not even taking into account you can't delete a component, you just reduce numb of components to 0 and hope it is there. Need a way documented way to delete a component implemented.  This seems to stem from the auto redraw with mouse over. slinging the cursor across the screen at a semi vert angle is what mostly causes this.

Might want to add shift click (or something) to add 5 or 10 components at a time. For things like large ships engines & armor this is sooooo useful.

**Comment by dahaic** [comment]
Can confirm the bug, non-selection is not well defined. Easiest solution is to have one of the designs selected by default (as non-selection wasn't meant to be editable, anyway).

Deletion of component is done for all zeroed ones when submitting design. This is deliberate choice to reduce clutter of the UI.

Shift click to add/remove 5 components is valid. Probably tight together with having proper help text for dialog.

**Comment by temuchin-** [comment]
I believe the code used to pull last design selected then falling back on 1st design in queue. Then it only acknowledged a design refresh upon a click to select the design. the idea of hovering select is nice. & totally not viable w/ mouse speed vs engine refresh rate.

Component deletion is recognized as a visual artifact, was wondering if it would be a bigger headache (from coding & usage perspective) to code a delete component action if num =1 , decrement num then would delete component. My gut feeling is that would create a headache on both ends. But always float an idea on the offchance that at sometime in the future it will not be painfully disastrous. 

adding the feature w/ help text feature sounds awesome. Now at some point soon (looking at myself possibly) this will need in game tutorial video / walkthru / documentation. Just because we code in that 3 left gestures w/ a downward swipe followed by a rapid set of left and right clicks will net you 25 extra battleships, does not mean the average player will intuit this feature.
