### ISSUE TITLE
Building on top of existing structure should benefit starting HP

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#235]
Current system of putting new structure into game with 10 % of HP is in general working well, it just makes TL3 upgrade of planets really significant setback regarding production of both CP and RP (upgrade of gov center is also quite delicate with the new system).

To make this phase more fluid, proposal is to replace structures in similar fashion ships are upgraded - based on the costs (recalculated according to current HP state), with maximum new status being for example 50 %.

As the repair time raises with logarithm of costs, it's still more efficient to build the final structure right away (thus no risk of micromanaging and first building factories just to replace them with TL3 variants few turns later)

**Comment by temuchin-** [comment]
right now in the game empire production only matters for offsetting ship maint, building ships, & building star gates. All other buildings are completed very fast, then you have to wait a preset time for the building to mature.

The proposed solution maybe a way to make production matter again, it is also a way to encourage micro managing.
