### ISSUE TITLE
Update account management to sane level

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#238]
There are currently multiple problems with the way accounts are handled in Outer Space. These all needs to get solved.

* passwords has to be stored hashed and salted properly in the database
* there needs to be API call to change the password (for admin to use it in case of problems)
* there needs to be dialog to change the password

**Comment by SummerGram** [comment]
mind to tell me the location of the code?

**Comment by dahaic** [comment]
If you don't mind, I will take this myself - I should be able to dedicate few hours today (I consider this one a release blocker, it's security related, and it's going to be all over the place).

**Comment by dahaic** [comment]
@SummerGram I have marked issues I feel appropriate with label "help needed", hope it helps!

**Comment by SummerGram** [comment]
@dahaic Sure
