### ISSUE TITLE
Need Sanity & functionality checks on the game playability at all levels (player skill / game types)

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#241]
In a nutshell. You need to run interactive test games on all galaxy types.  If my brief tests are indicator, then most (if not all) of the games are unwiinnable. I understand your desire to punish the players who don't know every way to optimize the game, & punish the players who do know every way optimize the game,,,,,,.
 Problem is that game designers want new players, w/o them games die, become irrelevant. The game was balanced. Allowing new players to cut their teeth with a learning curve, yet a learning curve they could manage w/o becoming frustrated & quitting.

Please run playtests, if the problem is me let me know. 

Current .5.7.3+ game tips.
1) if your starting empire does not have close easy access to 160+ min planets with 12 slots total of factory space (non contiguous, also this would mean  a 190 w/ 9 slots and spare planets to host power / food needs would work). Quit the game start a new empire.
2) if you have rebel empires in your area, do not ever contest anything they do unless it is for item number 1. The rebel empires will fall quickly to the mutants, cause 50 primitive fighters can't beat a mutie fleet of 15 fighters / 15 bombers.
3) Do not bother renegade colonies, they will also fall quickly, usually right after you do. So use them for your borders if you can.
4) do not research, if you must violate this code then research level 1, em wpn level 3 & flak battery.
5) do not worry about research path, you will never get high enough in the tech tree to care.
6) expect your fleet size to impose about a 70% production penalty, balance this w/ the reality that you will be losing about 1/3 of your forces in every engagement.
7) Mutants are monolithic w/o any penalties for spanning the entire galaxy, with the advent of primitive designs, quicker expansion with shortened building times,, you will lose. They already had ultimate multi purpose buildings w/ ridiculous HP / Atk, they have ships that are top of the line and won't be countered until you top Level 3, which you can't do.
8) do not take minor mutant territories, just  send occasional bombers. If you are lucky you can create a buffer zone for your empire w/ renegades, scorched earth & maybe a couple of rebel holdouts. This is your victory, if you can stabilize then begin to research & retool your empire for expansion. It feels like one in twelve games will get this result. I could be a tad too optimistic on my analysis.

The problem was, that the enemies didn't scale, now the problem is that players can never scale fast enough..........

If you are looking for a hard / normal / easy mode, then maybe we should look at implementing it. But the current changes have really skewed the game, making it unfun for anyone w/ little to no experience. I consider myself fairly competent at the game & find the idea of a nigh unwinnable game where you can never get ahead & will just lose,,, kinda not fun either.

**Comment by dahaic** [comment]
Thank you for this. Even though I do not fully agree with your assessment, as I believe you actually can win single player games even without re-rolling when neighborhood is not accommodating enough, there are some points that are spot on.

Rebel has been crippled with the addition of primitive technologies. This should be addressed by #230 . (And thus available in the next version). Also update of Renegade in #225 should yield some benefits, as rebels and players will be able to use trading with Renegades to secure bonus production and research over ostracized Mutant.

I do agree Mutant is not fun. Right now, it's, as you noted, all about that one moment where you stabilize. At that moment, you know you won. So I would love to finish slight update of Renegade and Mutant to actually research technologies. With that, we would have slow and weak Mutant at the start (together with pretty weak planets), which grows stronger in all aspects, so it can challenge you even in the later game. It's just one of the points that can make it better, but at the very least this one is already in works. Also what is definitely going to happen is lowering of Mutant and Renegade building HP (so when fully researched - fairly late game - it's going to be about what is it now).

For your game tips, I would replace most of them (except 2 and 3) with "build medium or large ships when fighting mutant".

And finally the interactive tests. I do actually play three games at this moment. I identified quite a lot of painpoints doing that. But to play everything as part of development, that's not feasible. Outer Space is not my job, and unless it's automated, such tests are not going to happen. And AI development (slow as it is) is meant to supplement this. When I update one of the AIs, I can look at the automated run and watch the effect, the same way I compared effects for 0.5.72 (videos on facebook). As the AIs share common code, it's hard to compare between versions, but I am aware something like that will have to be implemented.

**Comment by temuchin-** [comment]
Update the mutant force has went from 2K military to 10K military in 36 hours.... I have restabilized at 2K military (for now). My production is 555, there is about 9K.

I have not lost yet. Medium ships have been slowing down the mutants (had them for multi purpose, namely turn all my colony/fuel depots into defenders) but only if I have enough small ship ablative armor ships. Down to me & rebel faction 1, also renegade faction should be soaking up about 1/2 of his forces. I am actively engaged w/ 1/3 of his forces, we are playing stick and move. The rest of his forces are most likely enroute.

As for Intelligent agents (a more apt if still bold name for the computer players), I have someone who majored in the field of computer learning, possibly joining up, he has been farting around for a couple of months. Also Python has so much natively built in for deep learning, Intelligent agents, & expert systems.  So maybe the Comp Player gets a nice makeover.

I agree that the changes to Renegade production options will help them stabilize & maybe even hold their own.  Makes me sad, the window requirements to early game storm a renegade faction has gotten so much smaller (3 to 4 planet slot, single system very poor, maybe you can storm it.)

**Comment by temuchin-** [comment]
When you stabilize against the mutants, it does not mean you win. W/ how it now works ( w/ their forces always advancing), you start getting waves & some nasty ones. Especially where a random locus of movement occurs might have a force of 300 to 800 ships in it. Very nasty. & can destabilize your empire fast. So it seems to be something the comp player gets right. so now to work out how to leverage that going forward.

**Comment by temuchin-** [comment]
Well on 10 Sept 2018 the mutants had sent enough waves to overwhelm my empire. The game has moved on to 0.5.74 ..  Which changes enough parameters, that now tweaking mutants interaction w/ mutants, expansion, and scripting should clear up any deficiencies.

Mutants but head w/ other mutants when expanding, also are a bit slow on expansion when galactic radiation is high (maybe increase their scanner power?). Closing this issue, as it is not relevant.
