### ISSUE TITLE
Increase minimum population growth

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#243]
Current minimum population growth of 20/turn is too low. There is no significant gameplay reason for having this, it only slows down planet growth artificially, which can be workarounded by building outposts, but that is ugly micromanaging hack and not gameplay this game deserves. Proposing new value of 100 - that's current growth of 5k planet.

**Comment by SummerGram** [comment]
I can help in this issue.

**Comment by dahaic** [comment]
That would be great, @SummerGram . Do you need any pointers how to approach it/technicalities how to create a pull request with change?
