### ISSUE TITLE
Bug; Shipyard stacking bonuses.

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#277]
Sometimes when you build a shipyard (using civilian space docks ATM) you get increased repair bonus (5% + 5%) and increased refuel bonus (6% + 6%). The bonus seems to stack when you build both ship yards at about the same time. If you build a ship yard after the first one is completed the bonus does not stack.

Not sure if we should call this a bug or a feature.

**Comment by dahaic** [comment]
I have checked the code, and the behaviour is not obvious. Effects of the shipyards on the same planet stack. But only best planet (for each attribute separately) is taken into consideration.

As selection of the shipyard type is one of the big decisions of the player, I don't see too much of a reason for them to stack even on the planet.

**Comment by temuchin-** [comment]
The design of shipyards was intentional. (I have decided this after looking at the code for Scanner power, training facilities, and refueling).
