### ISSUE TITLE
Construction Dialog

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#284]
self.selectedDesignID = None

was how it used to be done. Now you have.....
        self.selectedDesignID = None
        self.highlightedDesignID = None
        self.editMode = False

plus the entirety of the cache and retreival.. Going through right now and making a version that does not have this. On faster systems than my test box this is not a problem. So this is probably a situation where the impact is less than 1% of all potential clients.

Problem is that the redraw in python is not that fast nor that efficient. So on older slower machines it will stutter and sometimes sputter , even skipping a design or two. w/ the redraw being a little iffy. You might select a design, and never know the actual design highlighted is another design until you take an irrereversible action like say deleting a ship class.

I'm thinking the best solution takes into account ergonomic UI design by moving the (New Dupe Scrap Construct) Line up to the top. This will make the user have to move their pointer less and have the most important options front and center, also drawing the eye to the ship information, making that section flow better.

 And then for the warning dialog increase the font when listing the design name / number. Also make that text a different color than the rest (taking into account the theme pack options when defining the color).

**Comment by dahaic** [comment]
@temuchin- can try the change I made in #285 ? I believe it should be enough even on low-spec machine.

**Comment by dahaic** [comment]
Update of confirmation dialog should fix this scenario.
